---
stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker build -t self_web .
    - docker rm -f self_web || true
    - docker run -d --name self_web -p 8501:8501 self_web
  only:
    - main
