variables:
  IMAGE_NAME: self_web
  CONTAINER_NAME: self_web

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t huyquang/$IMAGE_NAME:latest .
    - docker tag huyquang/$IMAGE_NAME huyquang/$IMAGE_NAME
    - docker push huyquang/$IMAGE_NAME
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d --name $CONTAINER_NAME -p 8501:8501 huyquang/$IMAGE_NAME
  only:
    - main
  tags:
    - docker
