---
variables:
  IMAGE_NAME: self_web
  SSH_USER: ubuntu
  SSH_HOST: 54.179.122.138

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t huyquang/$IMAGE_NAME .
    - docker tag huyquang/$IMAGE_NAME huyquang/$IMAGE_NAME
    - docker push huyquang/$IMAGE_NAME
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      docker pull $IMAGE_NAME && docker stop $IMAGE_NAME && docker rm $IMAGE_NAME && docker run -d --name $IMAGE_NAME -p 8501:8501 $IMAGE_NAME"
  only:
    - main
